---
# tasks file for install_jboss
- name: Register as user (joe_user) with password (somepass) and auto-subscribe to available content.
  redhat_subscription:
      state: present
      username: i-adarsh
      password: "{{ password }}"
      autosubscribe: true

- name: Creating Java Repository
  yum_repository:
      name: java
      description: JAVA YUM Repository
      baseurl: http://pkg.jenkins.io/redhat-stable
      gpgcheck: 1
                    
- name: Installing RPM Keys
  rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key


- name: Installing Java JDK and other softwares
  yum:
      name: 
            - java-11-openjdk-devel
            - unzip
      state: present
          
- name: Downloading JBoss
  get_url:
      url: "{{ jboss_eap_download_url }}"
      dest: "{{ jboss_eap_download_dir }}/{{ jboss_eap_zip_file }}"
  register: jboss_install
     
- name: Extracting JBoss
  unarchive:
      src: "{{ jboss_eap_download_dir }}/{{ jboss_eap_zip_file | basename }}"
      dest: "{{ jboss_eap_library_dest }}"
      creates: "{{ jboss_eap_jboss_home }}/version.txt"
      owner: "{{ jboss_eap_user }}"
      group: "{{ jboss_eap_group }}"
      mode: "{{ jboss_eap_mode }}"
      remote_src: yes
  when: jboss_install is changed
          
- name: Rename Directory
  command: "mv /jboss/{{ jboss_eap_dir_name }} /jboss/jboss"
  when: jboss_install is changed
                    
- name: Exporting ClassPath
  shell: "{{ item }}"
  loop:
        - "export JBOSS_HOME=/jboss/jboss/"
  when: jboss_install is changed
          
- name: Creating JBoss EAP Service 
  template:
      src: jboss.service.j2
      dest: /etc/systemd/system/jboss.service
            # script:
            #   cmd: script.sh
            # # shell: "{{ jboss_eap_home }}/bin/standalone.sh {{ cmd }}"
            # # vars:
            # #   cmd: >-
            # #     -b 0.0.0.0 &
            # # # shell: "/jboss/jboss/bin/./standalone.sh -b 0.0.0.0 &"
            # when: jboss_install is changed

- name: Starting Jboss EAP Service
  service:
      name: jboss.service
      state: started
            

...